version: "3.9"  # or any supported version
services:
  ui:
    build: .
    ports:
      - "3000:3000"
    container_name: ui-container
    volumes:
      - ./src:/app/src  # Link local ./src to /app/src inside container
      - ./public:/app/public